ALTER TABLE businesses
    ADD COLUMN update_at TIMESTAMP NULL,
    ADD COLUMN created_by VARCHAR(255) NULL,
    ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE users
    ADD COLUMN update_at TIMESTAMP NULL,
    ADD COLUMN created_by VARCHAR(255) NULL,
    ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE categories
    ADD COLUMN update_at TIMESTAMP NULL,
    ADD COLUMN created_by VARCHAR(255) NULL,
    ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE tickets
    ADD COLUMN update_at TIMESTAMP NULL,
    ADD COLUMN created_by VARCHAR(255) NULL,
    ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE notifications
    ADD COLUMN update_at TIMESTAMP NULL,
    ADD COLUMN created_by VARCHAR(255) NULL,
    ADD COLUMN updated_by VARCHAR(255) NULL;

UPDATE businesses SET update_at = created_at WHERE update_at IS NULL;
UPDATE users SET update_at = created_at WHERE update_at IS NULL;
UPDATE categories SET update_at = created_at WHERE update_at IS NULL;
UPDATE tickets SET update_at = created_at WHERE update_at IS NULL;
UPDATE notifications SET update_at = created_at WHERE update_at IS NULL;

ALTER TABLE businesses
    MODIFY COLUMN update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE users
    MODIFY COLUMN update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE categories
    MODIFY COLUMN update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE tickets
    MODIFY COLUMN update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE notifications
    MODIFY COLUMN update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;